### PR TITLE
Merge pull request #10 from QuewarG/new_member

### PR DESCRIPTION
**Pull request by OviedoSebastian**
Agregue información solicitada

### CODE REVIEW

**Review by QuewarG — APPROVED** [review]
Se revisa y esta OK

**Review by OviedoSebastian — COMMENTED** [review]
okay

**Comment by Camilo959** [comment]
wow, its ok

**Review by QuewarG — APPROVED** [review]
Ok

**Comment by Camilo959** [comment]
wow its ok x2

**Review by Camilo959 — APPROVED** [review]
WOW its ok x3

**Pull request merged**
